### PR TITLE
Gungy-Patch-1-Armor

### PR DESCRIPTION
**Pull request by Gungy**
Armor Updates

### CODE REVIEW

**Comment by Gungy** [comment]
Armor updates for test

**Comment by Thrax989** [comment]
Merge it into the test branch not master.

**Comment by Thrax989** [comment]
https://github.com/Thrax989/SWGFlurry/tree/TestServer

**Comment by Gungy** [comment]
wtf i chose test

**Comment by mikeface** [comment]
At quick glance, looks like some races were removed from armor?  Is that intended?

**Comment by Gungy** [comment]
shouldnt be

**Comment by Thrax989** [comment]
quick question I thought flurry server was not changing Armor ratings from light to anything else?

**Comment by Gungy** [comment]
i accidently added that file for storm trooper gloves

**Comment by Gungy** [comment]
everything else should still be light

**Comment by Gungy** [comment]
I'll be honest I suspect I'll need to nerf some of it with the flurry resource, my test resource sucked. but at least i will have a good idea what need reducing etc.

**Pull request merged**
